#include "airside/autonomy/scenario_loader.hpp"
#include "airside/autonomy/experiment.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <sstream>
#include <stdexcept>
#include <string>

namespace airside::autonomy {
namespace {
AutonomyScenario scenario(){return load_scenario(std::filesystem::path{AIRSIDE_SOURCE_DIR}/"scenarios/autonomy_tug.yaml");}
class MaximumCommand final:public IAutonomyController{public:VehicleCommand update(const SensorFrame&,const MissionState&)override{return{100.0,100.0};}};
}

TEST(AutonomyTest, AStarRouteBecomesAirportLocalWaypoints){AutonomySimulation sim{scenario(),42};ASSERT_EQ(sim.mission().waypoints.size(),3U);EXPECT_EQ(sim.mission().waypoints.front(),(Vec2{0,0}));EXPECT_EQ(sim.mission().goal,(Vec2{240,0}));}
TEST(AutonomyTest, IncrementalSnapshotSeparatesTruthFromSensorValues){AutonomySimulation sim{scenario(),42};ReferenceController controller;const auto before=sim.snapshot();EXPECT_DOUBLE_EQ(before.timestamp_s,0.0);ASSERT_TRUE(before.sensors.gnss);EXPECT_NE(before.ground_truth.position,before.sensors.gnss->position);EXPECT_TRUE(sim.advance(controller));const auto after=sim.snapshot();EXPECT_NEAR(after.timestamp_s,0.02,1e-9);EXPECT_GT(after.ground_truth.distance_m,0.0);}
TEST(AutonomyTest, SensorRatesAreIndependentAndTimestampsUseSimulationTime){auto s=scenario();s.timeout_s=2.0;AutonomySimulation sim{std::move(s),42};ReferenceController c;const auto r=sim.run(c);EXPECT_EQ(r.metrics.imu_samples,101U);EXPECT_EQ(r.metrics.odometry_samples,41U);EXPECT_EQ(r.metrics.lidar_scans,21U);EXPECT_EQ(r.metrics.gnss_samples,11U);EXPECT_NEAR(sim.observe().timestamp_s,sim.time_s(),1e-9);}
TEST(AutonomyTest, SameSeedProducesIdenticalClosedLoopDigestAndState){auto a=scenario(),b=scenario();AutonomySimulation first{std::move(a),42},second{std::move(b),42};ReferenceController c1,d1;const auto x=first.run(c1),y=second.run(d1);EXPECT_EQ(x.metrics.result,MissionResult::Success);EXPECT_EQ(x.metrics.trajectory_digest,y.metrics.trajectory_digest);EXPECT_EQ(x.final_state.position,y.final_state.position);EXPECT_EQ(x.metrics.gnss_samples,y.metrics.gnss_samples);EXPECT_EQ(x.metrics.lidar_scans,y.metrics.lidar_scans);}
TEST(AutonomyTest, DifferentSeedsChangeSensorAndTrajectoryDigest){AutonomySimulation a{scenario(),42},b{scenario(),43};ReferenceController c,d;const auto x=a.run(c),y=b.run(d);EXPECT_NE(x.metrics.trajectory_digest,y.metrics.trajectory_digest);EXPECT_EQ(x.metrics.result,MissionResult::Success);EXPECT_EQ(y.metrics.result,MissionResult::Success);}
TEST(AutonomyTest, CircleLidarReportsNearestHitAndMaximumRange){auto s=scenario();s.obstacles={{"near",{10,0},1.0},{"far",{15,0},1.0}};s.sensors.lidar_fov_rad=3.14159265358979323846;s.sensors.lidar_beams=3;s.sensors.lidar_sigma_m=0;s.initial_state.heading_rad=0;AutonomySimulation sim{std::move(s),7};const auto scan=sim.observe().lidar;ASSERT_TRUE(scan);ASSERT_EQ(scan->ranges_m.size(),3U);EXPECT_NEAR(scan->ranges_m[1],9.0,1e-9);EXPECT_DOUBLE_EQ(scan->ranges_m.front(),scan->range_max_m);EXPECT_DOUBLE_EQ(scan->ranges_m.front(),scan->ranges_m.back());EXPECT_GT(scan->angle_increment_rad,0.0);EXPECT_LT(scan->angle_min_rad,0.0);}
TEST(AutonomyTest, LidarRotatesAndTranslatesWithVehicle){auto s=scenario();s.obstacles={{"east",{10,5},1.0}};s.sensors.lidar_fov_rad=3.14159265358979323846;s.sensors.lidar_beams=3;s.sensors.lidar_sigma_m=0;s.initial_state.position={5,5};s.initial_state.heading_rad=0;AutonomySimulation sim{std::move(s),1};EXPECT_NEAR(sim.observe().lidar->ranges_m[1],4.0,1e-9);auto rotated=scenario();rotated.obstacles={{"north",{5,15},1.0}};rotated.sensors.lidar_fov_rad=3.14159265358979323846;rotated.sensors.lidar_beams=3;rotated.sensors.lidar_sigma_m=0;rotated.initial_state.position={5,5};rotated.initial_state.heading_rad=1.5707963267948966;AutonomySimulation turn{std::move(rotated),1};EXPECT_NEAR(turn.observe().lidar->ranges_m[1],9.0,1e-9);}
TEST(AutonomyTest, SensorNoiseIsDeterministicAndDifferentSeedsVary){auto a=scenario(),b=scenario(),c=scenario();a.sensors.lidar_beams=b.sensors.lidar_beams=c.sensors.lidar_beams=21;AutonomySimulation first{std::move(a),42},repeat{std::move(b),42},different{std::move(c),43};EXPECT_EQ(first.observe().lidar->ranges_m,repeat.observe().lidar->ranges_m);EXPECT_NE(first.observe().gnss->position,different.observe().gnss->position);}
TEST(AutonomyFaultTest, GnssDropoutHonorsHalfOpenSimulationIntervalAndRecordsEvents){auto s=scenario();s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Dropout,0.4,0.4});AutonomySimulation sim{std::move(s),42};ReferenceController c;for(int i=0;i<19;++i)ASSERT_TRUE(sim.advance(c));ASSERT_TRUE(sim.observe().gnss);ASSERT_TRUE(sim.advance(c));EXPECT_FALSE(sim.observe().gnss);for(int i=0;i<20;++i)ASSERT_TRUE(sim.advance(c));EXPECT_TRUE(sim.observe().gnss);const auto result=sim.run(c);EXPECT_DOUBLE_EQ(result.metrics.fault_activation_times_s.front(),0.4);EXPECT_NEAR(result.metrics.fault_deactivation_times_s.front(),0.8,1e-9);ASSERT_GE(result.metrics.fault_events.size(),5U);EXPECT_EQ(result.metrics.fault_events.front().event,"scheduled");EXPECT_EQ(result.metrics.fault_events[1].event,"activated");}
TEST(AutonomyFaultTest, LidarRangeLimitAndAngularMaskOnlyRemoveInformation){auto s=scenario();s.obstacles={{"forward",{8,0},1.0}};s.initial_state.heading_rad=0;s.sensors.lidar_sigma_m=0;s.sensors.lidar_beams=5;s.faults.push_back({SensorKind::Lidar,SensorFaultKind::RangeLimit,0.0,1.0,5.0});AutonomySimulation range{std::move(s),42};ASSERT_TRUE(range.observe().lidar);EXPECT_DOUBLE_EQ(range.observe().lidar->range_max_m,5.0);auto m=scenario();m.sensors.lidar_sigma_m=0;m.sensors.lidar_beams=5;m.faults.push_back({SensorKind::Lidar,SensorFaultKind::Obstruction,0.0,1.0,0.0,{},-0.01,0.01});AutonomySimulation mask{std::move(m),42};EXPECT_DOUBLE_EQ(mask.observe().lidar->ranges_m[2],mask.observe().lidar->range_max_m);}
TEST(AutonomyFaultTest, GnssBiasIsAppliedOnceToEachNewMeasurement){auto s=scenario();s.sensors.gnss_sigma_m=0;s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Bias,0.0,1.0,0.0,{4.0,-2.0}});AutonomySimulation sim{std::move(s),42};const auto first=sim.observe().gnss->position;EXPECT_DOUBLE_EQ(first.x_m,4.0);EXPECT_DOUBLE_EQ(first.y_m,-2.0);ReferenceController c;for(int i=0;i<10;++i)ASSERT_TRUE(sim.advance(c));EXPECT_LT(std::abs(sim.observe().gnss->position.x_m-first.x_m),0.5);}
TEST(AutonomyFaultTest, AddedGnssNoiseUsesFaultSeedAndUpdatesReportedAccuracy){auto make=[](){auto s=scenario();s.sensors.gnss_sigma_m=0;s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Noise,0.0,1.0,0.5});return s;};AutonomySimulation a{make(),42,77},b{make(),42,77},c{make(),42,78};ASSERT_TRUE(a.observe().gnss);EXPECT_EQ(a.observe().gnss->position,b.observe().gnss->position);EXPECT_NE(a.observe().gnss->position,c.observe().gnss->position);EXPECT_NEAR(a.observe().gnss->accuracy_m,0.98,1e-12);}
TEST(AutonomyFaultTest, ImuBiasAndWheelSlipAlterOnlyMeasurements){auto s=scenario();s.sensors.odometry_hz=50;s.sensors.odometry_sigma_m=0;s.sensors.odometry_sigma_mps=0;s.faults={{SensorKind::Imu,SensorFaultKind::Bias,0.0,1.0,0.2},{SensorKind::Odometry,SensorFaultKind::Scale,0.0,1.0,0.2}};AutonomySimulation sim{std::move(s),42};EXPECT_NEAR(sim.observe().imu->heading_rad,0.9853981633974483,0.01);ReferenceController c;ASSERT_TRUE(sim.advance(c));const auto frame=sim.observe();ASSERT_TRUE(frame.odometry);EXPECT_NEAR(frame.odometry->distance_m,sim.state().distance_m*0.8,0.002);}
TEST(AutonomyFaultTest, PacketLossSequenceUsesDedicatedFaultSeed){auto make=[](){auto s=scenario();s.timeout_s=2.0;s.faults.push_back({SensorKind::Gnss,SensorFaultKind::PacketLoss,0.0,2.0,0.0,{},0,0,0.5});return s;};AutonomySimulation a{make(),42,77},b{make(),42,77},c{make(),42,78};ReferenceController ca,cb,cc;const auto x=a.run(ca),y=b.run(cb),z=c.run(cc);EXPECT_EQ(x.metrics.messages_dropped,y.metrics.messages_dropped);EXPECT_EQ(x.metrics.trajectory_digest,y.metrics.trajectory_digest);EXPECT_NE(x.metrics.trajectory_digest,z.metrics.trajectory_digest);}
TEST(AutonomyFaultTest, DelayedAndBurstLossFaultsRecordDeterministicMetrics){auto s=scenario();s.timeout_s=1.0;s.faults={{SensorKind::Gnss,SensorFaultKind::Delay,0.2,0.4,0.1},{SensorKind::Imu,SensorFaultKind::BurstLoss,0.2,0.4}};AutonomySimulation sim{std::move(s),1,2};ReferenceController c;const auto result=sim.run(c);EXPECT_GT(result.metrics.messages_delayed,0U);EXPECT_DOUBLE_EQ(result.metrics.maximum_delay_s,0.1);EXPECT_GT(result.metrics.messages_dropped,0U);ASSERT_FALSE(result.metrics.fault_activation_times_s.empty());}
TEST(AutonomyFaultTest, DelayHoldsMeasurementUntilItsSimulationDeliveryTime){auto s=scenario();s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Delay,0.0,0.5,0.1});AutonomySimulation sim{std::move(s),1,2};EXPECT_FALSE(sim.observe().gnss);ReferenceController c;for(int i=0;i<4;++i)ASSERT_TRUE(sim.advance(c));EXPECT_FALSE(sim.observe().gnss);ASSERT_TRUE(sim.advance(c));ASSERT_TRUE(sim.observe().gnss);EXPECT_DOUBLE_EQ(sim.observe().gnss->timestamp_s,0.0);}
TEST(AutonomyFaultTest, ProlongedLidarLossTriggersControlledStopWithoutCollision){auto s=scenario();s.timeout_s=2.0;s.faults.push_back({SensorKind::Lidar,SensorFaultKind::Dropout,0.2,1.0});AutonomySimulation sim{std::move(s),42};ReferenceController c{2.2,0.2,3.0};const auto result=sim.run(c);EXPECT_EQ(result.metrics.result,MissionResult::Timeout);EXPECT_EQ(result.metrics.collision_count,0U);EXPECT_GT(result.metrics.safety_stop_entries,0U);EXPECT_GT(result.metrics.time_stopped_degraded_s,0.0);EXPECT_LT(result.metrics.time_stopped_degraded_s,1.5);}
TEST(AutonomyFaultTest, BriefGnssLossEntersDegradedModeButUsesDeadReckoning){auto s=scenario();s.timeout_s=2.0;s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Dropout,0.2,1.0});AutonomySimulation sim{std::move(s),42};ReferenceController c;const auto result=sim.run(c);EXPECT_EQ(result.metrics.collision_count,0U);EXPECT_GT(result.metrics.degraded_mode_entries,0U);EXPECT_EQ(result.metrics.safety_stop_entries,0U);}
TEST(AutonomyTest, VehicleEnforcesSpeedAndYawLimits){auto s=scenario();s.obstacles.clear();s.timeout_s=0.5;AutonomySimulation sim{std::move(s),2};MaximumCommand controller;const auto result=sim.run(controller);EXPECT_LE(result.final_state.speed_mps,sim.mission().limits.maximum_speed_mps);EXPECT_LE(std::abs(result.final_state.yaw_rate_radps),sim.mission().limits.maximum_yaw_rate_radps);}
TEST(AutonomyTest, LidarSafetyStopsBeforePhysicalCollision){auto s=scenario();s.obstacles={{"safety-barrier",{4,0},0.8}};s.initial_state.heading_rad=0;s.safety_stop_range_m=4.5;s.timeout_s=0.5;AutonomySimulation sim{std::move(s),42};ReferenceController controller{4.5};const auto result=sim.run(controller);EXPECT_EQ(result.metrics.result,MissionResult::Timeout);EXPECT_GT(result.metrics.emergency_stops,0U);EXPECT_EQ(result.metrics.safety_stop_entries,1U);EXPECT_EQ(result.metrics.collision_count,0U);EXPECT_DOUBLE_EQ(result.metrics.time_stopped_degraded_s,0.0);EXPECT_DOUBLE_EQ(result.final_state.distance_m,0.0);}
TEST(AutonomyTest, IndependentCollisionSystemRecordsImpact){auto s=scenario();s.obstacles={{"blocking-barrier",{0,0},0.8}};AutonomySimulation sim{std::move(s),42};MaximumCommand controller;const auto result=sim.run(controller);EXPECT_EQ(result.metrics.result,MissionResult::Collision);EXPECT_EQ(result.metrics.collision_count,1U);ASSERT_TRUE(result.metrics.first_collision_time_s);EXPECT_EQ(result.metrics.collided_obstacle,"blocking-barrier");}
TEST(AutonomyTest, OptionalTrajectoryRecordingHasGroundTruthAndObservationColumns){AutonomySimulation sim{scenario(),42};ReferenceController controller;std::ostringstream csv;const auto result=sim.run(controller,&csv);const auto contents=csv.str();EXPECT_EQ(result.metrics.result,MissionResult::Success);EXPECT_NE(contents.find("estimated_x_m"),std::string::npos);EXPECT_GT(std::count(contents.begin(),contents.end(),'\n'),2);}
TEST(AutonomyExperimentTest, SerialAndParallelRunsHaveStableOrdinalAndIdenticalResults){std::vector<AutonomyRunRequest> requests;for(std::size_t i=0;i<6;++i){auto s=scenario();s.sensors.gnss_sigma_m=i%2?.1:1.5;requests.push_back({std::move(s),42+i,10-i});}const auto serial=execute_runs(requests,1),parallel=execute_runs(std::move(requests),3);ASSERT_EQ(serial.runs.size(),parallel.runs.size());for(std::size_t i=0;i<serial.runs.size();++i){EXPECT_EQ(serial.runs[i].ordinal,parallel.runs[i].ordinal);EXPECT_EQ(serial.runs[i].seed,parallel.runs[i].seed);EXPECT_EQ(serial.runs[i].metrics.result,parallel.runs[i].metrics.result);EXPECT_EQ(serial.runs[i].metrics.trajectory_digest,parallel.runs[i].metrics.trajectory_digest);}}
TEST(AutonomyExperimentTest, WorkerFailurePropagatesToCaller){auto s=scenario();s.sensors.gnss_hz=0.0;EXPECT_THROW((void)execute_runs({AutonomyRunRequest{std::move(s),42,0}},2),std::invalid_argument);}
TEST(AutonomyFaultYamlTest, LoadsFaultSchemaAndRejectsMalformedIntervals){const auto source=std::filesystem::path{AIRSIDE_SOURCE_DIR}/"scenarios/autonomy_tug.yaml";const auto temp=std::filesystem::temp_directory_path()/("ramplab_fault_yaml_"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));std::filesystem::create_directories(temp);std::filesystem::copy_file(source.parent_path()/"baseline.yaml",temp/"baseline.yaml");std::ifstream in(source);std::string yaml((std::istreambuf_iterator<char>(in)),{});const auto good=temp/"good.yaml";{std::ofstream out(good);out<<yaml<<"\nfaults:\n  - {sensor: gnss, type: dropout, start_s: 2.0, duration_s: 1.0}\n";}const auto loaded=load_scenario(good);ASSERT_EQ(loaded.faults.size(),1U);EXPECT_EQ(loaded.faults.front().sensor,SensorKind::Gnss);const auto bad=temp/"bad.yaml";{std::ofstream out(bad);out<<yaml<<"\nfaults:\n  - {sensor: gnss, type: dropout, start_s: 2.0, duration_s: 0.0}\n";}EXPECT_THROW((void)load_scenario(bad),std::runtime_error);std::filesystem::remove_all(temp);}
}
