#include "airside/autonomy/scenario_loader.hpp"
#include "airside/autonomy/experiment.hpp"
#include "airside/autonomy/state_estimator.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <sstream>
#include <stdexcept>
#include <string>

namespace airside::autonomy {
namespace {
AutonomyScenario scenario(){return load_scenario(std::filesystem::path{AIRSIDE_SOURCE_DIR}/"scenarios/autonomy_tug.yaml");}
class MaximumCommand final:public IAutonomyController{public:VehicleCommand update(const SensorFrame&,const MissionState&)override{return{100.0,100.0};}};
}

TEST(AutonomyTest, AStarRouteBecomesAirportLocalWaypoints){AutonomySimulation sim{scenario(),42};ASSERT_EQ(sim.mission().waypoints.size(),3U);EXPECT_EQ(sim.mission().waypoints.front(),(Vec2{0,0}));EXPECT_EQ(sim.mission().goal,(Vec2{240,0}));}
TEST(StateEstimatorTest, InitializesOnlyFromGnssAndMaintainsFiniteCovariance){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{3,-2},0.98};f.imu=ImuMeasurement{0,0.4,0,0};f.odometry=OdometryMeasurement{0,0,0,0};const auto&s=e.update(f);EXPECT_TRUE(s.initialized);EXPECT_NEAR(s.position.x_m,3,1e-12);EXPECT_NEAR(s.heading_rad,0.4,1e-12);EXPECT_EQ(s.gnss_accepted,1U);for(double v:s.covariance)EXPECT_TRUE(std::isfinite(v));}
TEST(StateEstimatorTest, WheelIncrementIsIntegratedOnceAcrossVariableMeasurementIntervals){EstimatorConfig c;c.gnss_sigma_m=0.01;StateEstimator2D e(c);SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},0.02};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,2,0};(void)e.update(f);f={};f.timestamp_s=0.02;f.imu=ImuMeasurement{0.02,0,0,0};(void)e.update(f);f.timestamp_s=0.05;f.imu=ImuMeasurement{0.05,0,0,0};f.odometry=OdometryMeasurement{0.05,0.1,2,0};const auto&s=e.update(f);EXPECT_NEAR(s.position.x_m,0.1,1e-9);EXPECT_NEAR(s.position.y_m,0,1e-9);}
TEST(StateEstimatorTest, TurningPredictionAndYawWrappingRemainBounded){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},0.98};f.imu=ImuMeasurement{0,3.13,0,0};f.odometry=OdometryMeasurement{0,0,1,0};(void)e.update(f);f={};f.timestamp_s=0.1;f.imu=ImuMeasurement{0.1,-3.13,0.2,0};f.odometry=OdometryMeasurement{0.1,0.1,1,0.023};const auto&s=e.update(f);EXPECT_NEAR(std::abs(s.heading_rad),3.13,0.03);EXPECT_NEAR(s.position.x_m,-0.1,0.01);}
TEST(StateEstimatorTest, GatesOutlyingGnssAndRejectsStaleTimestamps){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},0.98};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,0,0};(void)e.update(f);f.timestamp_s=0.2;f.gnss=GnssMeasurement{0.2,{100,100},0.98};const auto&g=e.update(f);EXPECT_EQ(g.gnss_rejected,1U);EXPECT_EQ(g.gate_activations,1U);f.timestamp_s=1.0;f.gnss=GnssMeasurement{0.3,{0,0},0.98};const auto&s=e.update(f);EXPECT_EQ(s.stale_rejected,1U);}
TEST(StateEstimatorTest, PositionCovarianceGrowsWithoutAbsoluteFixAndContractsWhenFixReturns){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},0.98};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,1,0};(void)e.update(f);const double initial=e.state().position_uncertainty_m;f={};f.timestamp_s=4;f.imu=ImuMeasurement{4,0,0,0};f.odometry=OdometryMeasurement{4,0,1,0};const double lost=e.update(f).position_uncertainty_m;EXPECT_GT(lost,initial);f.timestamp_s=4.02;f.gnss=GnssMeasurement{4.02,{4.02,0},0.98};f.imu=ImuMeasurement{4.02,0,0,0};const double returned=e.update(f).position_uncertainty_m;EXPECT_LT(returned,lost);}
TEST(StateEstimatorTest, RejectsMalformedConfiguration){EstimatorConfig c;c.unsafe_position_sigma_m=c.degraded_position_sigma_m;EXPECT_THROW(StateEstimator2D{c},std::invalid_argument);}
TEST(StateEstimatorTest, WheelHealthStartsNominalAndIgnoresOneTransientDisagreement){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},0.98};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,1,0};(void)e.update(f);for(int i=1;i<=200;++i){const double t=i*.02;f.timestamp_s=t;f.imu=ImuMeasurement{t,0,0,0};if(i%10==0)f.gnss=GnssMeasurement{t,{t,0},.98};if(i%5==0)f.odometry=OdometryMeasurement{t,t,1,0};(void)e.update(f);}EXPECT_EQ(e.state().wheel_health,WheelHealth::Nominal);}
TEST(StateEstimatorTest, SustainedWheelScaleErrorDegradesAndDownweightsThenRecovers){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},.98};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,1,0};(void)e.update(f);for(int i=1;i<=600;++i){const double t=i*.02;f.timestamp_s=t;f.imu=ImuMeasurement{t,0,0,0};if(i%10==0)f.gnss=GnssMeasurement{t,{t,0},.98};if(i%5==0)f.odometry=OdometryMeasurement{t,.75*t,.75,0};(void)e.update(f);}EXPECT_EQ(e.state().wheel_health,WheelHealth::Degraded);EXPECT_GT(e.state().wheel_inconsistency_count,1U);EXPECT_GT(e.state().wheel_downweighted,0U);for(int i=601;i<=1800;++i){const double t=i*.02;f.timestamp_s=t;f.imu=ImuMeasurement{t,0,0,0};if(i%10==0)f.gnss=GnssMeasurement{t,{t,0},.98};if(i%5==0)f.odometry=OdometryMeasurement{t,.75*12.0+(t-12.0),1,0};(void)e.update(f);}EXPECT_EQ(e.state().wheel_health,WheelHealth::Nominal);}
TEST(StateEstimatorTest, RepeatedConsistentGnssReacquiresWithBoundedCorrectionsAndSafetyHealth){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{20,0},.98};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,0,0};(void)e.update(f);double previous=e.state().position.x_m;for(int i=1;i<=80;++i){const double t=i*.2;f.timestamp_s=t;f.gnss=GnssMeasurement{t,{0.1*std::sin(t),0},.98};f.imu=ImuMeasurement{t,0,0,0};f.odometry=OdometryMeasurement{t,0,0,0};const auto&s=e.update(f);EXPECT_LE(std::hypot(s.position.x_m-previous,s.position.y_m),0.751);if(s.gnss_recovery==GnssRecoveryState::Reacquiring)EXPECT_EQ(s.health,EstimatorHealth::Unsafe);previous=s.position.x_m;if(s.gnss_recovery==GnssRecoveryState::Recovered)break;}EXPECT_GT(e.state().reacquisition_attempts,0U);EXPECT_EQ(e.state().reacquisition_successes,1U);EXPECT_EQ(e.state().gnss_recovery,GnssRecoveryState::Recovered);EXPECT_LT(std::abs(e.state().position.x_m),1.0);EXPECT_NE(e.state().health,EstimatorHealth::Unsafe);}
TEST(StateEstimatorTest, InconsistentMovingGnssCandidatesCannotConfirmRecovery){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{20,0},.98};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,0,0};(void)e.update(f);for(int i=1;i<=40;++i){const double t=i*.2,angle=(i%8)*0.7853981633974483;f.timestamp_s=t;f.gnss=GnssMeasurement{t,{10*std::cos(angle),10*std::sin(angle)},.98};f.imu=ImuMeasurement{t,0,0,0};f.odometry=OdometryMeasurement{t,0,0,0};(void)e.update(f);}EXPECT_EQ(e.state().gnss_recovery,GnssRecoveryState::Inconsistent);EXPECT_EQ(e.state().reacquisition_successes,0U);EXPECT_EQ(e.state().reacquisition_attempts,0U);EXPECT_GT(e.state().reacquisition_candidates_rejected,0U);}
TEST(StateEstimatorTest, IsolatedGnssOutlierDoesNotStartReacquisition){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},.98};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,0,0};(void)e.update(f);f.timestamp_s=.2;f.gnss=GnssMeasurement{.2,{100,100},.98};(void)e.update(f);EXPECT_EQ(e.state().reacquisition_attempts,0U);EXPECT_EQ(e.state().reacquisition_successes,0U);EXPECT_EQ(e.state().gnss_recovery,GnssRecoveryState::Inconsistent);}
TEST(StateEstimatorTest, RemainsUninitializedUntilPositionAndHeadingAreAvailable){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{1,2},0.98};EXPECT_FALSE(e.update(f).initialized);f.timestamp_s=0.02;f.imu=ImuMeasurement{0.02,0.7,0,0};EXPECT_TRUE(e.update(f).initialized);EXPECT_NEAR(e.state().heading_rad,0.7,1e-12);}
TEST(StateEstimatorTest, WheelSlipFlowsThroughOdometrySpeedAndImuDropoutUsesOdometryHeading){StateEstimator2D nominal,slip;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},0.98};f.imu=ImuMeasurement{0,0,0,0};f.odometry=OdometryMeasurement{0,0,1,0};(void)nominal.update(f);(void)slip.update(f);f={};f.timestamp_s=0.1;f.odometry=OdometryMeasurement{0.1,0.1,1,0.2};const auto a=nominal.update(f);f.odometry->distance_m=0.075;f.odometry->speed_mps=0.75;const auto b=slip.update(f);EXPECT_NEAR(a.position.x_m,0.1,0.01);EXPECT_NEAR(b.position.x_m,0.1,0.01);f.timestamp_s=0.2;f.odometry.reset();const auto next_nominal=nominal.update(f);const auto next_slip=slip.update(f);EXPECT_GT(next_nominal.position.x_m,next_slip.position.x_m);EXPECT_NEAR(next_nominal.heading_rad,0.2,0.02);}
TEST(StateEstimatorTest, CovarianceStaysFiniteSymmetricAndNonnegativeAcrossRepeatedUpdates){StateEstimator2D e;SensorFrame f;f.timestamp_s=0;f.gnss=GnssMeasurement{0,{0,0},0.98};f.imu=ImuMeasurement{0,0,0.1,0};f.odometry=OdometryMeasurement{0,0,1,0};(void)e.update(f);for(int i=1;i<=100;++i){const double t=0.02*static_cast<double>(i);f.timestamp_s=t;if(i%1==0)f.imu=ImuMeasurement{t,0.1*t,0.1,0};if(i%3==0)f.odometry=OdometryMeasurement{t,0.02*static_cast<double>(i/3),1,0.1*t};if(i%10==0)f.gnss=GnssMeasurement{t,{0.1*t,0.005*t*t},0.98};const auto&s=e.update(f);for(std::size_t r=0;r<4;++r){EXPECT_GE(s.covariance[r*4+r],0.0);for(std::size_t c=0;c<4;++c){EXPECT_TRUE(std::isfinite(s.covariance[r*4+c]));EXPECT_NEAR(s.covariance[r*4+c],s.covariance[c*4+r],1e-10);}}}}
TEST(StateEstimatorTest, RepeatedSameMeasurementSequenceProducesIdenticalState){auto execute=[](){StateEstimator2D e;SensorFrame f;for(int i=0;i<30;++i){f.timestamp_s=0.02*i;f.imu=ImuMeasurement{f.timestamp_s,0.01*i,0.02,0};f.odometry=OdometryMeasurement{f.timestamp_s,0.05*i,1,0.0004*i};if(i%10==0)f.gnss=GnssMeasurement{f.timestamp_s,{0.05*i,0},0.98};(void)e.update(f);}return e.state();};const auto a=execute(),b=execute();EXPECT_EQ(a.position,b.position);EXPECT_DOUBLE_EQ(a.heading_rad,b.heading_rad);EXPECT_EQ(a.covariance,b.covariance);EXPECT_EQ(a.gnss_accepted,b.gnss_accepted);}
TEST(AutonomyTest, IncrementalSnapshotSeparatesTruthFromSensorValues){AutonomySimulation sim{scenario(),42};ReferenceController controller;const auto before=sim.snapshot();EXPECT_DOUBLE_EQ(before.timestamp_s,0.0);ASSERT_TRUE(before.sensors.gnss);EXPECT_NE(before.ground_truth.position,before.sensors.gnss->position);EXPECT_TRUE(sim.advance(controller));const auto after=sim.snapshot();EXPECT_NEAR(after.timestamp_s,0.02,1e-9);EXPECT_GT(after.ground_truth.distance_m,0.0);}
TEST(AutonomyTest, SensorRatesAreIndependentAndTimestampsUseSimulationTime){auto s=scenario();s.timeout_s=2.0;AutonomySimulation sim{std::move(s),42};ReferenceController c;const auto r=sim.run(c);EXPECT_EQ(r.metrics.imu_samples,101U);EXPECT_EQ(r.metrics.odometry_samples,41U);EXPECT_EQ(r.metrics.lidar_scans,21U);EXPECT_EQ(r.metrics.gnss_samples,11U);EXPECT_NEAR(sim.observe().timestamp_s,sim.time_s(),1e-9);}
TEST(AutonomyTest, RepeatedSeedRecordsIdenticalDeliveredObservationStream){auto execute=[](){auto s=scenario();s.timeout_s=0.3;AutonomySimulation sim{std::move(s),91};ReferenceController c;std::ostringstream stream;const auto r=sim.run(c,nullptr,&stream);return std::pair{stream.str(),r.metrics.sensor_stream_digest};};const auto a=execute(),b=execute();EXPECT_EQ(a.first,b.first);EXPECT_EQ(a.second,b.second);EXPECT_FALSE(a.first.empty());}
TEST(AutonomyTest, SameSeedProducesIdenticalClosedLoopDigestAndState){auto a=scenario(),b=scenario();AutonomySimulation first{std::move(a),42},second{std::move(b),42};ReferenceController c1,d1;const auto x=first.run(c1),y=second.run(d1);EXPECT_EQ(x.metrics.result,MissionResult::Success);EXPECT_EQ(x.metrics.trajectory_digest,y.metrics.trajectory_digest);EXPECT_EQ(x.final_state.position,y.final_state.position);EXPECT_EQ(x.metrics.gnss_samples,y.metrics.gnss_samples);EXPECT_EQ(x.metrics.lidar_scans,y.metrics.lidar_scans);}
TEST(AutonomyTest, DifferentSeedsChangeSensorAndTrajectoryDigest){AutonomySimulation a{scenario(),42},b{scenario(),43};ReferenceController c,d;const auto x=a.run(c),y=b.run(d);EXPECT_NE(x.metrics.trajectory_digest,y.metrics.trajectory_digest);EXPECT_EQ(x.metrics.result,MissionResult::Success);EXPECT_EQ(y.metrics.result,MissionResult::Success);}
TEST(AutonomyTest, LegacyLocalizationModePreservesGoal7Seed42Digest){auto s=scenario();s.estimator_enabled=false;AutonomySimulation sim{std::move(s),42};ReferenceController c;const auto r=sim.run(c);EXPECT_EQ(r.metrics.result,MissionResult::Success);EXPECT_EQ(r.metrics.trajectory_digest,1488735950019943363ULL);}
TEST(AutonomyTest, CircleLidarReportsNearestHitAndMaximumRange){auto s=scenario();s.obstacles={{"near",{10,0},1.0},{"far",{15,0},1.0}};s.sensors.lidar_fov_rad=3.14159265358979323846;s.sensors.lidar_beams=3;s.sensors.lidar_sigma_m=0;s.initial_state.heading_rad=0;AutonomySimulation sim{std::move(s),7};const auto scan=sim.observe().lidar;ASSERT_TRUE(scan);ASSERT_EQ(scan->ranges_m.size(),3U);EXPECT_NEAR(scan->ranges_m[1],9.0,1e-9);EXPECT_DOUBLE_EQ(scan->ranges_m.front(),scan->range_max_m);EXPECT_DOUBLE_EQ(scan->ranges_m.front(),scan->ranges_m.back());EXPECT_GT(scan->angle_increment_rad,0.0);EXPECT_LT(scan->angle_min_rad,0.0);}
TEST(AutonomyTest, LidarRotatesAndTranslatesWithVehicle){auto s=scenario();s.obstacles={{"east",{10,5},1.0}};s.sensors.lidar_fov_rad=3.14159265358979323846;s.sensors.lidar_beams=3;s.sensors.lidar_sigma_m=0;s.initial_state.position={5,5};s.initial_state.heading_rad=0;AutonomySimulation sim{std::move(s),1};EXPECT_NEAR(sim.observe().lidar->ranges_m[1],4.0,1e-9);auto rotated=scenario();rotated.obstacles={{"north",{5,15},1.0}};rotated.sensors.lidar_fov_rad=3.14159265358979323846;rotated.sensors.lidar_beams=3;rotated.sensors.lidar_sigma_m=0;rotated.initial_state.position={5,5};rotated.initial_state.heading_rad=1.5707963267948966;AutonomySimulation turn{std::move(rotated),1};EXPECT_NEAR(turn.observe().lidar->ranges_m[1],9.0,1e-9);}
TEST(AutonomyTest, SensorNoiseIsDeterministicAndDifferentSeedsVary){auto a=scenario(),b=scenario(),c=scenario();a.sensors.lidar_beams=b.sensors.lidar_beams=c.sensors.lidar_beams=21;AutonomySimulation first{std::move(a),42},repeat{std::move(b),42},different{std::move(c),43};EXPECT_EQ(first.observe().lidar->ranges_m,repeat.observe().lidar->ranges_m);EXPECT_NE(first.observe().gnss->position,different.observe().gnss->position);}
TEST(AutonomyFaultTest, GnssDropoutHonorsHalfOpenSimulationIntervalAndRecordsEvents){auto s=scenario();s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Dropout,0.4,0.4});AutonomySimulation sim{std::move(s),42};ReferenceController c;for(int i=0;i<19;++i)ASSERT_TRUE(sim.advance(c));ASSERT_TRUE(sim.observe().gnss);ASSERT_TRUE(sim.advance(c));EXPECT_FALSE(sim.observe().gnss);for(int i=0;i<20;++i)ASSERT_TRUE(sim.advance(c));EXPECT_TRUE(sim.observe().gnss);const auto result=sim.run(c);EXPECT_DOUBLE_EQ(result.metrics.fault_activation_times_s.front(),0.4);EXPECT_NEAR(result.metrics.fault_deactivation_times_s.front(),0.8,1e-9);ASSERT_GE(result.metrics.fault_events.size(),5U);EXPECT_EQ(result.metrics.fault_events.front().event,"scheduled");EXPECT_EQ(result.metrics.fault_events[1].event,"activated");}
TEST(AutonomyFaultTest, LidarRangeLimitAndAngularMaskOnlyRemoveInformation){auto s=scenario();s.obstacles={{"forward",{8,0},1.0}};s.initial_state.heading_rad=0;s.sensors.lidar_sigma_m=0;s.sensors.lidar_beams=5;s.faults.push_back({SensorKind::Lidar,SensorFaultKind::RangeLimit,0.0,1.0,5.0});AutonomySimulation range{std::move(s),42};ASSERT_TRUE(range.observe().lidar);EXPECT_DOUBLE_EQ(range.observe().lidar->range_max_m,5.0);auto m=scenario();m.sensors.lidar_sigma_m=0;m.sensors.lidar_beams=5;m.faults.push_back({SensorKind::Lidar,SensorFaultKind::Obstruction,0.0,1.0,0.0,{},-0.01,0.01});AutonomySimulation mask{std::move(m),42};EXPECT_DOUBLE_EQ(mask.observe().lidar->ranges_m[2],mask.observe().lidar->range_max_m);}
TEST(AutonomyFaultTest, GnssBiasIsAppliedOnceToEachNewMeasurement){auto s=scenario();s.sensors.gnss_sigma_m=0;s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Bias,0.0,1.0,0.0,{4.0,-2.0}});AutonomySimulation sim{std::move(s),42};const auto first=sim.observe().gnss->position;EXPECT_DOUBLE_EQ(first.x_m,4.0);EXPECT_DOUBLE_EQ(first.y_m,-2.0);ReferenceController c;for(int i=0;i<10;++i)ASSERT_TRUE(sim.advance(c));EXPECT_LT(std::abs(sim.observe().gnss->position.x_m-first.x_m),0.5);}
TEST(AutonomyFaultTest, AddedGnssNoiseUsesFaultSeedAndUpdatesReportedAccuracy){auto make=[](){auto s=scenario();s.sensors.gnss_sigma_m=0;s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Noise,0.0,1.0,0.5});return s;};AutonomySimulation a{make(),42,77},b{make(),42,77},c{make(),42,78};ASSERT_TRUE(a.observe().gnss);EXPECT_EQ(a.observe().gnss->position,b.observe().gnss->position);EXPECT_NE(a.observe().gnss->position,c.observe().gnss->position);EXPECT_NEAR(a.observe().gnss->accuracy_m,0.98,1e-12);}
TEST(AutonomyFaultTest, ImuBiasAndWheelSlipAlterOnlyMeasurements){auto s=scenario();s.sensors.odometry_hz=50;s.sensors.odometry_sigma_m=0;s.sensors.odometry_sigma_mps=0;s.faults={{SensorKind::Imu,SensorFaultKind::Bias,0.0,1.0,0.2},{SensorKind::Odometry,SensorFaultKind::Scale,0.0,1.0,0.2}};AutonomySimulation sim{std::move(s),42};EXPECT_NEAR(sim.observe().imu->heading_rad,0.9853981633974483,0.01);ReferenceController c;ASSERT_TRUE(sim.advance(c));const auto frame=sim.observe();ASSERT_TRUE(frame.odometry);EXPECT_NEAR(frame.odometry->distance_m,sim.state().distance_m*0.8,0.002);}
TEST(AutonomyFaultTest, PacketLossSequenceUsesDedicatedFaultSeed){auto make=[](){auto s=scenario();s.timeout_s=2.0;s.faults.push_back({SensorKind::Gnss,SensorFaultKind::PacketLoss,0.0,2.0,0.0,{},0,0,0.5});return s;};AutonomySimulation a{make(),42,77},b{make(),42,77},c{make(),42,78};ReferenceController ca,cb,cc;const auto x=a.run(ca),y=b.run(cb),z=c.run(cc);EXPECT_EQ(x.metrics.messages_dropped,y.metrics.messages_dropped);EXPECT_EQ(x.metrics.trajectory_digest,y.metrics.trajectory_digest);EXPECT_NE(x.metrics.trajectory_digest,z.metrics.trajectory_digest);}
TEST(AutonomyFaultTest, DelayedAndBurstLossFaultsRecordDeterministicMetrics){auto s=scenario();s.timeout_s=1.0;s.faults={{SensorKind::Gnss,SensorFaultKind::Delay,0.2,0.4,0.1},{SensorKind::Imu,SensorFaultKind::BurstLoss,0.2,0.4}};AutonomySimulation sim{std::move(s),1,2};ReferenceController c;const auto result=sim.run(c);EXPECT_GT(result.metrics.messages_delayed,0U);EXPECT_DOUBLE_EQ(result.metrics.maximum_delay_s,0.1);EXPECT_GT(result.metrics.messages_dropped,0U);ASSERT_FALSE(result.metrics.fault_activation_times_s.empty());}
TEST(AutonomyFaultTest, DelayHoldsMeasurementUntilItsSimulationDeliveryTime){auto s=scenario();s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Delay,0.0,0.5,0.1});AutonomySimulation sim{std::move(s),1,2};EXPECT_FALSE(sim.observe().gnss);ReferenceController c;for(int i=0;i<4;++i)ASSERT_TRUE(sim.advance(c));EXPECT_FALSE(sim.observe().gnss);ASSERT_TRUE(sim.advance(c));ASSERT_TRUE(sim.observe().gnss);EXPECT_DOUBLE_EQ(sim.observe().gnss->timestamp_s,0.0);}
TEST(AutonomyFaultTest, ProlongedLidarLossTriggersControlledStopWithoutCollision){auto s=scenario();s.timeout_s=2.0;s.faults.push_back({SensorKind::Lidar,SensorFaultKind::Dropout,0.2,1.0});AutonomySimulation sim{std::move(s),42};ReferenceController c{2.2,0.2,3.0};const auto result=sim.run(c);EXPECT_EQ(result.metrics.result,MissionResult::Timeout);EXPECT_EQ(result.metrics.collision_count,0U);EXPECT_GT(result.metrics.safety_stop_entries,0U);EXPECT_GT(result.metrics.time_stopped_degraded_s,0.0);EXPECT_LT(result.metrics.time_stopped_degraded_s,1.5);}
TEST(AutonomyFaultTest, BriefGnssLossEntersDegradedModeButUsesDeadReckoning){auto s=scenario();s.timeout_s=2.0;s.faults.push_back({SensorKind::Gnss,SensorFaultKind::Dropout,0.2,1.0});AutonomySimulation sim{std::move(s),42};ReferenceController c;const auto result=sim.run(c);EXPECT_EQ(result.metrics.collision_count,0U);EXPECT_GT(result.metrics.degraded_mode_entries,0U);EXPECT_EQ(result.metrics.safety_stop_entries,0U);}
TEST(AutonomyFaultTest, LongLocalizationLossTransitionsUnsafeStopsAndRecovers){auto s=scenario();s.faults={{SensorKind::Gnss,SensorFaultKind::Dropout,5.0,25.0},{SensorKind::Imu,SensorFaultKind::Dropout,5.0,25.0},{SensorKind::Odometry,SensorFaultKind::Dropout,5.0,25.0}};s.timeout_s=120.0;AutonomySimulation sim{std::move(s),42,7001};ReferenceController c;const auto result=sim.run(c);EXPECT_EQ(result.metrics.result,MissionResult::Success);EXPECT_EQ(result.metrics.collision_count,0U);EXPECT_EQ(result.metrics.estimator_uncertainty_safety_stops,1U);EXPECT_GT(result.metrics.estimator_degraded_time_s,0.0);EXPECT_GT(result.metrics.estimator_unsafe_time_s,0.0);EXPECT_TRUE(std::ranges::any_of(result.metrics.estimator_events,[](const auto&e){return e.event=="estimator_unsafe";}));EXPECT_TRUE(std::ranges::any_of(result.metrics.estimator_events,[](const auto&e){return e.event=="estimator_healthy";}));}
TEST(AutonomyTest, VehicleEnforcesSpeedAndYawLimits){auto s=scenario();s.obstacles.clear();s.timeout_s=0.5;AutonomySimulation sim{std::move(s),2};MaximumCommand controller;const auto result=sim.run(controller);EXPECT_LE(result.final_state.speed_mps,sim.mission().limits.maximum_speed_mps);EXPECT_LE(std::abs(result.final_state.yaw_rate_radps),sim.mission().limits.maximum_yaw_rate_radps);}
TEST(AutonomyTest, LidarSafetyStopsBeforePhysicalCollision){auto s=scenario();s.obstacles={{"safety-barrier",{4,0},0.8}};s.initial_state.heading_rad=0;s.safety_stop_range_m=4.5;s.timeout_s=0.5;AutonomySimulation sim{std::move(s),42};ReferenceController controller{4.5};const auto result=sim.run(controller);EXPECT_EQ(result.metrics.result,MissionResult::Timeout);EXPECT_GT(result.metrics.emergency_stops,0U);EXPECT_EQ(result.metrics.safety_stop_entries,1U);EXPECT_EQ(result.metrics.collision_count,0U);EXPECT_DOUBLE_EQ(result.metrics.time_stopped_degraded_s,0.0);EXPECT_DOUBLE_EQ(result.final_state.distance_m,0.0);}
TEST(AutonomyTest, IndependentCollisionSystemRecordsImpact){auto s=scenario();s.obstacles={{"blocking-barrier",{0,0},0.8}};AutonomySimulation sim{std::move(s),42};MaximumCommand controller;const auto result=sim.run(controller);EXPECT_EQ(result.metrics.result,MissionResult::Collision);EXPECT_EQ(result.metrics.collision_count,1U);ASSERT_TRUE(result.metrics.first_collision_time_s);EXPECT_EQ(result.metrics.collided_obstacle,"blocking-barrier");}
TEST(AutonomyTest, OptionalTrajectoryRecordingHasGroundTruthAndObservationColumns){AutonomySimulation sim{scenario(),42};ReferenceController controller;std::ostringstream csv;const auto result=sim.run(controller,&csv);const auto contents=csv.str();EXPECT_EQ(result.metrics.result,MissionResult::Success);EXPECT_NE(contents.find("estimated_x_m"),std::string::npos);EXPECT_GT(std::count(contents.begin(),contents.end(),'\n'),2);}
TEST(AutonomyExperimentTest, SerialAndParallelRunsHaveStableOrdinalAndIdenticalResults){std::vector<AutonomyRunRequest> requests;for(std::size_t i=0;i<6;++i){auto s=scenario();s.sensors.gnss_sigma_m=i%2?.1:1.5;requests.push_back({std::move(s),42+i,10-i});}const auto serial=execute_runs(requests,1),parallel=execute_runs(std::move(requests),3);ASSERT_EQ(serial.runs.size(),parallel.runs.size());for(std::size_t i=0;i<serial.runs.size();++i){const auto&a=serial.runs[i].metrics;const auto&b=parallel.runs[i].metrics;EXPECT_EQ(serial.runs[i].ordinal,parallel.runs[i].ordinal);EXPECT_EQ(serial.runs[i].seed,parallel.runs[i].seed);EXPECT_EQ(a.result,b.result);EXPECT_EQ(a.trajectory_digest,b.trajectory_digest);EXPECT_DOUBLE_EQ(a.mean_position_error_m,b.mean_position_error_m);EXPECT_DOUBLE_EQ(a.rms_position_error_m,b.rms_position_error_m);EXPECT_DOUBLE_EQ(a.maximum_position_error_m,b.maximum_position_error_m);EXPECT_DOUBLE_EQ(a.final_position_error_m,b.final_position_error_m);EXPECT_DOUBLE_EQ(a.mean_heading_error_rad,b.mean_heading_error_rad);EXPECT_DOUBLE_EQ(a.maximum_heading_error_rad,b.maximum_heading_error_rad);EXPECT_DOUBLE_EQ(a.final_heading_error_rad,b.final_heading_error_rad);EXPECT_DOUBLE_EQ(a.estimator_initialization_time_s,b.estimator_initialization_time_s);EXPECT_DOUBLE_EQ(a.estimator_healthy_time_s,b.estimator_healthy_time_s);EXPECT_DOUBLE_EQ(a.estimator_degraded_time_s,b.estimator_degraded_time_s);EXPECT_DOUBLE_EQ(a.estimator_unsafe_time_s,b.estimator_unsafe_time_s);EXPECT_DOUBLE_EQ(a.maximum_position_uncertainty_m,b.maximum_position_uncertainty_m);EXPECT_DOUBLE_EQ(a.maximum_heading_uncertainty_rad,b.maximum_heading_uncertainty_rad);EXPECT_EQ(a.gnss_updates_accepted,b.gnss_updates_accepted);EXPECT_EQ(a.gnss_updates_rejected,b.gnss_updates_rejected);EXPECT_EQ(a.stale_measurements_rejected,b.stale_measurements_rejected);EXPECT_EQ(a.gnss_gate_activations,b.gnss_gate_activations);EXPECT_EQ(a.estimator_uncertainty_safety_stops,b.estimator_uncertainty_safety_stops);}}
TEST(AutonomyExperimentTest, WorkerFailurePropagatesToCaller){auto s=scenario();s.sensors.gnss_hz=0.0;EXPECT_THROW((void)execute_runs({AutonomyRunRequest{std::move(s),42,0}},2),std::invalid_argument);}
TEST(AutonomyExperimentTest, Goal9DiagnosticsAreIdenticalAcrossSerialAndParallelRuns){std::vector<AutonomyRunRequest> requests;for(std::size_t i=0;i<4;++i){auto s=scenario();s.name="diagnostic_"+std::to_string(i);s.faults.push_back({SensorKind::Odometry,SensorFaultKind::Scale,20.0,45.0,0.15});requests.push_back({std::move(s),42+i,i,7001+i});}const auto serial=execute_runs(requests,1),parallel=execute_runs(std::move(requests),3);ASSERT_EQ(serial.runs.size(),parallel.runs.size());for(std::size_t i=0;i<serial.runs.size();++i){const auto&a=serial.runs[i].metrics;const auto&b=parallel.runs[i].metrics;EXPECT_EQ(a.wheel_inconsistency_count,b.wheel_inconsistency_count);EXPECT_EQ(a.wheel_downweighted,b.wheel_downweighted);EXPECT_EQ(a.gnss_reacquisition_attempts,b.gnss_reacquisition_attempts);EXPECT_EQ(a.gnss_reacquisition_successes,b.gnss_reacquisition_successes);EXPECT_EQ(a.gnss_reacquisition_candidates_rejected,b.gnss_reacquisition_candidates_rejected);EXPECT_DOUBLE_EQ(a.localization_degraded_time_s,b.localization_degraded_time_s);EXPECT_DOUBLE_EQ(a.maximum_gnss_nis,b.maximum_gnss_nis);EXPECT_DOUBLE_EQ(a.estimator_safety_stop_time_s,b.estimator_safety_stop_time_s);EXPECT_DOUBLE_EQ(a.gnss_recovery_latency_s,b.gnss_recovery_latency_s);EXPECT_EQ(a.final_wheel_health,b.final_wheel_health);EXPECT_EQ(a.final_gnss_recovery,b.final_gnss_recovery);}}
TEST(AutonomyFaultYamlTest, LoadsFaultSchemaAndRejectsMalformedIntervals){const auto source=std::filesystem::path{AIRSIDE_SOURCE_DIR}/"scenarios/autonomy_tug.yaml";const auto temp=std::filesystem::temp_directory_path()/("ramplab_fault_yaml_"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));std::filesystem::create_directories(temp);std::filesystem::copy_file(source.parent_path()/"baseline.yaml",temp/"baseline.yaml");std::ifstream in(source);std::string yaml((std::istreambuf_iterator<char>(in)),{});const auto good=temp/"good.yaml";{std::ofstream out(good);out<<yaml<<"\nfaults:\n  - {sensor: gnss, type: dropout, start_s: 2.0, duration_s: 1.0}\n";}const auto loaded=load_scenario(good);ASSERT_EQ(loaded.faults.size(),1U);EXPECT_EQ(loaded.faults.front().sensor,SensorKind::Gnss);const auto bad=temp/"bad.yaml";{std::ofstream out(bad);out<<yaml<<"\nfaults:\n  - {sensor: gnss, type: dropout, start_s: 2.0, duration_s: 0.0}\n";}EXPECT_THROW((void)load_scenario(bad),std::runtime_error);std::filesystem::remove_all(temp);}
}
