if(NOT DEFINED AIRSIDE_CLI OR NOT DEFINED AIRSIDE_SOURCE_DIR OR NOT DEFINED AIRSIDE_OUTPUT_DIR)
    message(FATAL_ERROR "Surface export test requires CLI, source, and output paths")
endif()
file(MAKE_DIRECTORY "${AIRSIDE_OUTPUT_DIR}")

set(control_scenario "${AIRSIDE_SOURCE_DIR}/scenarios/surface_traffic.yaml")
set(disrupted_scenario "${AIRSIDE_SOURCE_DIR}/scenarios/surface_traffic_disrupted.yaml")
set(control_json "${AIRSIDE_OUTPUT_DIR}/control.json")
set(control_csv "${AIRSIDE_OUTPUT_DIR}/control.csv")
set(control_events "${AIRSIDE_OUTPUT_DIR}/control.jsonl")
set(repeat_events "${AIRSIDE_OUTPUT_DIR}/repeat.jsonl")
set(disrupted_json "${AIRSIDE_OUTPUT_DIR}/disrupted.json")
set(lifecycle_scenario "${AIRSIDE_SOURCE_DIR}/scenarios/turnaround_lifecycle.yaml")
set(lifecycle_disrupted_scenario "${AIRSIDE_SOURCE_DIR}/scenarios/turnaround_lifecycle_disrupted.yaml")
set(lifecycle_json "${AIRSIDE_OUTPUT_DIR}/lifecycle.json")
set(lifecycle_csv "${AIRSIDE_OUTPUT_DIR}/lifecycle.csv")
set(lifecycle_events "${AIRSIDE_OUTPUT_DIR}/lifecycle.jsonl")
set(lifecycle_repeat_events "${AIRSIDE_OUTPUT_DIR}/lifecycle-repeat.jsonl")
set(lifecycle_disrupted_json "${AIRSIDE_OUTPUT_DIR}/lifecycle-disrupted.json")

execute_process(COMMAND "${AIRSIDE_CLI}" --scenario "${control_scenario}" --seed 42
    --metrics-json "${control_json}" --metrics-csv "${control_csv}" --record-events "${control_events}" --quiet
    RESULT_VARIABLE control_result ERROR_VARIABLE control_error)
if(NOT control_result EQUAL 0)
    message(FATAL_ERROR "Control CLI failed: ${control_error}")
endif()
execute_process(COMMAND "${AIRSIDE_CLI}" --scenario "${control_scenario}" --seed 42
    --record-events "${repeat_events}" --quiet RESULT_VARIABLE repeat_result ERROR_VARIABLE repeat_error)
if(NOT repeat_result EQUAL 0)
    message(FATAL_ERROR "Repeated control CLI failed: ${repeat_error}")
endif()
execute_process(COMMAND "${AIRSIDE_CLI}" --scenario "${disrupted_scenario}" --seed 42
    --metrics-json "${disrupted_json}" --quiet RESULT_VARIABLE disrupted_result ERROR_VARIABLE disrupted_error)
if(NOT disrupted_result EQUAL 0)
    message(FATAL_ERROR "Disrupted CLI failed: ${disrupted_error}")
endif()

file(READ "${control_json}" control_data)
string(JSON control_departed GET "${control_data}" surface departed_aircraft)
string(JSON control_total GET "${control_data}" surface total_aircraft)
string(JSON throughput GET "${control_data}" surface departure_throughput_per_hour)
string(JSON collisions_aa GET "${control_data}" surface aircraft_aircraft_collisions)
string(JSON collisions_ag GET "${control_data}" surface aircraft_ground_collisions)
if(NOT control_departed EQUAL 3 OR NOT control_total EQUAL 3 OR NOT throughput GREATER 0 OR
   NOT collisions_aa EQUAL 0 OR NOT collisions_ag EQUAL 0)
    message(FATAL_ERROR "Control JSON surface metrics are incomplete or unexpected")
endif()

file(STRINGS "${control_csv}" csv_lines)
list(GET csv_lines 0 csv_header)
foreach(field IN ITEMS surface_departure_throughput_per_hour surface_aircraft_aircraft_collisions
        surface_aircraft_ground_collisions minimum_aircraft_separation_m minimum_aircraft_ground_separation_m
        pushback_started_at_seconds pushback_completed_at_seconds taxi_started_at_seconds
        taxi_completed_at_seconds runway_queue_entered_at_seconds)
    string(FIND "${csv_header}" "${field}" field_index)
    if(field_index EQUAL -1)
        message(FATAL_ERROR "Control CSV is missing ${field}")
    endif()
endforeach()

file(READ "${control_events}" control_event_text)
file(READ "${repeat_events}" repeat_event_text)
if(NOT control_event_text STREQUAL repeat_event_text)
    message(FATAL_ERROR "Repeated seed-42 JSONL event output differs")
endif()
file(STRINGS "${control_events}" event_lines)
set(previous_sequence -1)
set(event_types "")
foreach(event_line IN LISTS event_lines)
    string(JSON sequence GET "${event_line}" sequence)
    string(JSON event_type GET "${event_line}" type)
    if(sequence LESS_EQUAL previous_sequence)
        message(FATAL_ERROR "JSONL sequence is not strictly increasing")
    endif()
    set(previous_sequence "${sequence}")
    list(APPEND event_types "${event_type}")
endforeach()
foreach(required_event IN ITEMS SurfacePushbackStarted SurfacePushbackCompleted SurfaceTaxiRouteAssigned
        SurfaceReservationAcquired SurfaceReservationReleased SurfaceRunwayQueueEntered
        SurfaceRunwayClearance AircraftDeparted)
    if(NOT required_event IN_LIST event_types)
        message(FATAL_ERROR "JSONL is missing ${required_event}")
    endif()
endforeach()

file(READ "${disrupted_json}" disrupted_data)
string(JSON reroutes GET "${disrupted_data}" surface reroutes)
string(JSON safe_failures GET "${disrupted_data}" surface safe_failures)
if(reroutes LESS 1 OR NOT safe_failures EQUAL 0)
    message(FATAL_ERROR "Disrupted JSON does not record a successful reroute")
endif()

execute_process(COMMAND "${AIRSIDE_CLI}" --scenario "${lifecycle_scenario}" --seed 42
    --metrics-json "${lifecycle_json}" --metrics-csv "${lifecycle_csv}"
    --record-events "${lifecycle_events}" --quiet
    RESULT_VARIABLE lifecycle_result ERROR_VARIABLE lifecycle_error)
if(NOT lifecycle_result EQUAL 0)
    message(FATAL_ERROR "Integrated lifecycle CLI failed: ${lifecycle_error}")
endif()
execute_process(COMMAND "${AIRSIDE_CLI}" --scenario "${lifecycle_scenario}" --seed 42
    --record-events "${lifecycle_repeat_events}" --quiet
    RESULT_VARIABLE lifecycle_repeat_result ERROR_VARIABLE lifecycle_repeat_error)
if(NOT lifecycle_repeat_result EQUAL 0)
    message(FATAL_ERROR "Repeated integrated lifecycle CLI failed: ${lifecycle_repeat_error}")
endif()
execute_process(COMMAND "${AIRSIDE_CLI}" --scenario "${lifecycle_disrupted_scenario}" --seed 42
    --metrics-json "${lifecycle_disrupted_json}" --quiet
    RESULT_VARIABLE lifecycle_disrupted_result ERROR_VARIABLE lifecycle_disrupted_error)
if(NOT lifecycle_disrupted_result EQUAL 0)
    message(FATAL_ERROR "Integrated disruption CLI failed: ${lifecycle_disrupted_error}")
endif()

file(READ "${lifecycle_json}" lifecycle_data)
string(JSON lifecycle_completed GET "${lifecycle_data}" completed_turnarounds)
string(JSON lifecycle_arrivals GET "${lifecycle_data}" surface arrivals_completed)
string(JSON lifecycle_departures GET "${lifecycle_data}" surface departed_aircraft)
string(JSON lifecycle_gate_assignments GET "${lifecycle_data}" surface gate_assignments)
string(JSON lifecycle_gate_occupancy GET "${lifecycle_data}" surface gate_occupancy_seconds)
string(JSON lifecycle_fleet_collisions GET "${lifecycle_data}" fleet collisions)
string(JSON lifecycle_aircraft_collisions GET "${lifecycle_data}" surface aircraft_aircraft_collisions)
string(JSON lifecycle_ground_collisions GET "${lifecycle_data}" surface aircraft_ground_collisions)
if(NOT lifecycle_completed EQUAL 3 OR NOT lifecycle_arrivals EQUAL 2 OR NOT lifecycle_departures EQUAL 3 OR
   NOT lifecycle_gate_assignments EQUAL 2 OR NOT lifecycle_gate_occupancy GREATER 0 OR
   NOT lifecycle_fleet_collisions EQUAL 0 OR NOT lifecycle_aircraft_collisions EQUAL 0 OR
   NOT lifecycle_ground_collisions EQUAL 0)
    message(FATAL_ERROR "Integrated lifecycle metrics are incomplete or unsafe")
endif()
file(READ "${lifecycle_events}" lifecycle_event_text)
file(READ "${lifecycle_repeat_events}" lifecycle_repeat_event_text)
if(NOT lifecycle_event_text STREQUAL lifecycle_repeat_event_text)
    message(FATAL_ERROR "Repeated integrated seed-42 JSONL event output differs")
endif()
file(STRINGS "${lifecycle_events}" lifecycle_event_lines)
set(previous_sequence -1)
set(aircraft_three_sequence 0)
set(aircraft_three_events "")
foreach(event_line IN LISTS lifecycle_event_lines)
    string(JSON sequence GET "${event_line}" sequence)
    string(JSON event_type GET "${event_line}" type)
    string(JSON aircraft_id ERROR_VARIABLE missing_aircraft GET "${event_line}" aircraft_id)
    if(sequence LESS_EQUAL previous_sequence)
        message(FATAL_ERROR "Integrated lifecycle JSONL sequence is not strictly increasing")
    endif()
    set(previous_sequence "${sequence}")
    if(NOT missing_aircraft AND aircraft_id EQUAL 3)
        math(EXPR aircraft_three_sequence "${aircraft_three_sequence} + 1")
        set(aircraft_three_event_${aircraft_three_sequence} "${event_type}")
    endif()
endforeach()
foreach(required_event IN ITEMS AircraftLanded ArrivalTaxiInStarted GateAssigned ArrivalAtGate
        TurnaroundStarted TurnaroundReadyForDeparture PushbackTaxiOutStarted
        SurfaceRunwayQueueEntered AircraftDeparted)
    set(found_event FALSE)
    foreach(index RANGE 1 ${aircraft_three_sequence})
        if("${aircraft_three_event_${index}}" STREQUAL "${required_event}")
            set(found_event TRUE)
        endif()
    endforeach()
    if(NOT found_event)
        message(FATAL_ERROR "Aircraft 3 lifecycle is missing ${required_event}")
    endif()
endforeach()

file(READ "${lifecycle_disrupted_json}" lifecycle_disrupted_data)
string(JSON control_ar502_departure GET "${lifecycle_data}" turnarounds 2 actual_departure_seconds)
string(JSON disrupted_ar502_departure GET "${lifecycle_disrupted_data}" turnarounds 2 actual_departure_seconds)
math(EXPR propagated_delay "${disrupted_ar502_departure} - ${control_ar502_departure}")
if(NOT propagated_delay EQUAL 460)
    message(FATAL_ERROR "Expected 460 s disruption propagation to AR502 departure, got ${propagated_delay}")
endif()
string(JSON disrupted_collisions GET "${lifecycle_disrupted_data}" surface aircraft_ground_collisions)
if(NOT disrupted_collisions EQUAL 0)
    message(FATAL_ERROR "Integrated disruption caused aircraft-ground collisions")
endif()
